### ISSUE TITLE
Create Sequelize Models

### ISSUE THREAD

**Issue by beefbones** [beefbones/hydro-home#5]

**Comment by ckester99** [comment]
## Need to create ORM models and associations according to the following schema:
![image](https://user-images.githubusercontent.com/43022124/214460890-d0664a8a-4bb4-4e54-b909-ba605cc79a7c.png)
 ## The following Models will need to be created:
- [x] User
- [x] ForumPost
- [x] PostComments
- [x] WaterConsumption

**Comment by ckester99** [comment]
Database schema is built and models are defined
